version: '3.8'

services:
  backend:
    build: .
    container_name: jabarulin-backend
    restart: unless-stopped
    ports:
      - "${PORT:-5000}:5000"
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - jabarulin-network
    volumes:
      - ./:/app
      - /app/node_modules

  db:
    image: mongo:7
    container_name: jabarulin-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - jabarulin-network

networks:
  jabarulin-network:
    driver: bridge

volumes:
  mongo-data: